(() => {
  'use strict';

  const core=globalThis.FilamentInventoryScan;
  if(!core)return;
  const STORAGE_KEY='filament-inventory-v1';
  const STYLE_HREF='/css/components/scan.css';
  let stream=null,detector=null,scanFrame=0,scanning=false,detecting=false,lastDetectionAt=0,pendingUnknown='';
  let startingCamera=false,torchOn=false,scannerProfile='',scannerSession=0;
  const currentProfile=()=>globalThis.FilamentInventoryUsers?.currentUser?.()||'Bill';
  const parse=(text,fallback=null)=>{try{return JSON.parse(text);}catch{return fallback;}};
  const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const $=id=>document.getElementById(id);

  function readState(){
    const value=parse(localStorage.getItem(STORAGE_KEY)||'{}',{});
    return Array.isArray(value?.spools)?value:{spools:[]};
  }
  function findSpool(id){const wanted=String(id||'').trim().toLowerCase();return readState().spools.find(spool=>String(spool?.id||'').trim().toLowerCase()===wanted)||null;}
  function liveScanningSupported(){return Boolean(globalThis.BarcodeDetector&&navigator.mediaDevices?.getUserMedia&&window.isSecureContext);}
  function beginScannerSession(){scannerSession+=1;scannerProfile=currentProfile();return scannerSession;}
  function invalidateScannerSession(){scannerSession+=1;scannerProfile='';}
  function activeProfileMatches(){
    if(!scannerProfile||scannerProfile===currentProfile())return true;
    stopCamera();
    setCapability('Inventory changed','warning');
    setStatus('<strong>Inventory changed.</strong> Close and reopen the scanner before scanning or entering an ID.','warning');
    const start=$('qrStartCamera');if(start)start.disabled=true;
    return false;
  }

  function ensureStyles(){
    if(document.querySelector(`link[data-fi-scan-style="${STYLE_HREF}"]`))return;
    const link=document.createElement('link');
    link.rel='stylesheet';link.href=STYLE_HREF;link.dataset.fiScanStyle=STYLE_HREF;document.head.appendChild(link);
  }

  function scannerMarkup(){return `<div class="dialog-head qr-scanner-head"><div><span class="eyebrow">Scan spool</span><h3 id="qrScannerTitle">Scan a filament spool</h3><p>Scan the durable spool ID. Inventory details stay in the app, not in the QR code.</p></div><button class="btn icon-btn" type="button" data-scanner-close aria-label="Close scanner">×</button></div><div class="dialog-body qr-scanner-body"><div class="qr-scanner-context"><span class="qr-profile-pill"><span>Active inventory</span><strong data-scanner-profile></strong></span><span class="qr-capability" data-scanner-capability>Checking camera…</span></div><section class="qr-camera-stage" data-camera-active="false"><div class="qr-video-shell" id="qrVideoShell" hidden><video class="qr-video" id="qrScannerVideo" muted playsinline></video><div class="qr-reticle" aria-hidden="true"><span></span></div><span class="qr-live-pill" aria-hidden="true">Scanning</span></div><div class="qr-camera-idle" data-camera-idle><span class="qr-camera-mark" aria-hidden="true">⌁</span><strong>Ready to scan</strong><p>Keep the QR label inside the frame. The camera starts automatically when supported.</p><button class="btn btn-primary" id="qrStartCamera" type="button">Start camera</button></div></section><div class="qr-scan-status" id="qrScanStatus" role="status" aria-live="polite" data-tone="neutral"><strong>Ready.</strong> Point at a Filament Inventory label.</div><div class="qr-camera-controls" aria-label="Camera controls"><button class="btn" id="qrTorchCamera" type="button" hidden aria-pressed="false">Flashlight</button><button class="btn" id="qrStopCamera" type="button" disabled>Pause camera</button></div><div class="qr-scan-fallback" id="qrScanFallback" hidden><strong>Use Apple Camera or Code Scanner</strong><p>On iPhone and iPad, the system QR scanner is the most reliable option. A Filament Inventory label opens the matching spool in your active inventory.</p></div><details class="qr-manual-details" id="qrManualDetails"><summary>Enter spool ID instead</summary><form class="qr-manual" id="qrManualForm"><label class="sr-only" for="qrManualId">Spool ID</label><input class="field" id="qrManualId" autocomplete="off" autocapitalize="characters" maxlength="32" placeholder="Spool ID, e.g. S022"><button class="btn" type="submit">Find spool</button></form></details><section class="qr-recent-section" aria-labelledby="qrRecentTitle"><div class="qr-recent-head"><div><span class="eyebrow">Quick access</span><strong id="qrRecentTitle">Recent spools</strong></div><span>Active inventory only</span></div><div class="qr-recent-list" id="qrRecentSpools"></div></section></div>`;}

  function ensureDialogs(){
    ensureStyles();
    if(!$('qrScannerDialog')){const dialog=document.createElement('dialog');dialog.id='qrScannerDialog';dialog.className='qr-scanner-dialog';dialog.setAttribute('aria-labelledby','qrScannerTitle');dialog.innerHTML=scannerMarkup();document.body.appendChild(dialog);dialog.addEventListener('close',()=>{invalidateScannerSession();stopCamera();});dialog.querySelector('[data-scanner-close]')?.addEventListener('click',()=>dialog.close());$('qrStartCamera')?.addEventListener('click',()=>startCamera({automatic:false,session:scannerSession}));$('qrStopCamera')?.addEventListener('click',stopCamera);$('qrTorchCamera')?.addEventListener('click',toggleTorch);$('qrManualForm')?.addEventListener('submit',event=>{event.preventDefault();processScanValue($('qrManualId')?.value||'');});}
    if(!document.querySelector('.qr-unknown-dialog')){const dialog=document.createElement('dialog');dialog.className='qr-unknown-dialog';dialog.setAttribute('aria-labelledby','qrUnknownTitle');dialog.innerHTML=`<div class="dialog-head"><div><span class="eyebrow">Scan result</span><h3 id="qrUnknownTitle" data-unknown-title>Spool not found here</h3></div><button class="btn icon-btn" type="button" data-unknown-close aria-label="Close">×</button></div><div class="dialog-body"><p class="fi-confirm-copy">This is a valid spool ID, but it is not in the active private inventory on this device. Sync if you expect it here, or review intake before adding it.</p><div class="qr-unknown-actions"><button class="btn" type="button" data-unknown-scan>Scan another</button><button class="btn" type="button" data-unknown-sync>Sync inventory</button><button class="btn btn-primary" type="button" data-unknown-add>Review intake</button></div></div>`;document.body.appendChild(dialog);}
  }

  function ensureLaunchButton(){let button=document.querySelector('.scan-launch');if(button){button.setAttribute('title','Scan spool');return button;}const host=document.querySelector('.top-actions');if(!host)return null;button=document.createElement('button');button.id='qrScanLaunch';button.type='button';button.className='btn scan-launch header-scan-launch';button.setAttribute('aria-label','Scan spool');button.setAttribute('aria-haspopup','dialog');button.setAttribute('aria-controls','qrScannerDialog');button.setAttribute('title','Scan spool');button.innerHTML='<span aria-hidden="true">⌁</span><span>Scan</span>';button.addEventListener('click',openScanner);host.prepend(button);return button;}
  function setStatus(html,tone='neutral'){const node=$('qrScanStatus');if(!node)return;node.innerHTML=html;node.dataset.tone=tone;}
  function setCapability(text,tone='neutral'){const node=document.querySelector('[data-scanner-capability]');if(!node)return;node.textContent=text;node.dataset.tone=tone;}
  function setCameraUi(active){const shell=$('qrVideoShell'),start=$('qrStartCamera'),stop=$('qrStopCamera'),stage=document.querySelector('.qr-camera-stage');if(shell)shell.hidden=!active;if(start)start.disabled=active||startingCamera;if(stop)stop.disabled=!active;if(stage)stage.dataset.cameraActive=String(active);}

  function renderRecent(){const holder=$('qrRecentSpools');if(!holder)return;const rows=(readState().spools||[]).filter(spool=>spool&&!spool.archivedAt).slice().sort((a,b)=>new Date(b.updatedAt||b.createdAt||0)-new Date(a.updatedAt||a.createdAt||0)).slice(0,4);holder.replaceChildren();if(!rows.length){const empty=document.createElement('span');empty.className='qr-recent-empty';empty.textContent='No recent spools in this inventory yet.';holder.appendChild(empty);return;}for(const spool of rows){const button=document.createElement('button');button.type='button';button.className='qr-recent-spool';button.dataset.scannerRecentId=spool.id;button.setAttribute('aria-label',`Open ${spool.id}, ${spool.colorName||'unknown color'}`);const swatch=document.createElement('i');swatch.setAttribute('aria-hidden','true');swatch.style.backgroundColor=/^#[0-9a-f]{6}$/i.test(spool.colorHex||'')?spool.colorHex:'#64748b';const copy=document.createElement('span'),title=document.createElement('strong'),detail=document.createElement('small'),arrow=document.createElement('b');title.textContent=`${spool.id} · ${spool.colorName||'Unknown color'}`;detail.textContent=`${spool.brand||'Unknown'} · ${spool.material||'Unknown'}`;copy.append(title,detail);arrow.setAttribute('aria-hidden','true');arrow.textContent='›';button.append(swatch,copy,arrow);holder.appendChild(button);}}

  function openScanner(){ensureDialogs();ensureLaunchButton();const session=beginScannerSession(),dialog=$('qrScannerDialog'),fallback=$('qrScanFallback'),start=$('qrStartCamera'),manual=$('qrManualDetails'),profile=dialog?.querySelector('[data-scanner-profile]'),supported=liveScanningSupported();if(profile)profile.textContent=currentProfile();if(fallback)fallback.hidden=supported;if(start){start.hidden=!supported;start.disabled=false;}if(manual)manual.open=!supported;renderRecent();setCameraUi(false);setCapability(supported?'Camera available':'Manual / device scan','neutral');setStatus(supported?'<strong>Starting camera…</strong> Hold a Filament Inventory QR inside the frame.':'<strong>Live camera scanning is unavailable here.</strong> Use your device QR scanner or enter the spool ID.','neutral');if(dialog&&!dialog.open)dialog.showModal();if(supported)requestAnimationFrame(()=>startCamera({automatic:true,session}));else $('qrManualId')?.focus();}
  function closeScanner(){const dialog=$('qrScannerDialog');if(dialog?.open)dialog.close();else{invalidateScannerSession();stopCamera();}}

  async function startCamera({automatic=false,session=scannerSession}={}){if(session!==scannerSession||!activeProfileMatches()||startingCamera||scanning)return;if(!liveScanningSupported()){const fallback=$('qrScanFallback'),manual=$('qrManualDetails');if(fallback)fallback.hidden=false;if(manual)manual.open=true;setCapability('Manual / device scan','warning');$('qrManualId')?.focus();return;}startingCamera=true;setCameraUi(false);setCapability('Opening camera…','neutral');let candidate=null;try{if(typeof BarcodeDetector.getSupportedFormats==='function'){const formats=await BarcodeDetector.getSupportedFormats();if(session!==scannerSession||!activeProfileMatches())return;if(Array.isArray(formats)&&!formats.includes('qr_code'))throw new Error('QR detection is not supported by this browser.');}detector=new BarcodeDetector({formats:['qr_code']});candidate=await navigator.mediaDevices.getUserMedia({audio:false,video:{facingMode:{ideal:'environment'},width:{ideal:1920},height:{ideal:1080}}});if(session!==scannerSession||!activeProfileMatches()){candidate.getTracks?.().forEach(track=>track.stop());return;}stream=candidate;const video=$('qrScannerVideo');if(!video)throw new Error('Scanner video surface is unavailable.');video.srcObject=stream;const track=stream.getVideoTracks?.()[0]||stream.getTracks?.()[0];const capabilities=track?.getCapabilities?.()||{};const torch=$('qrTorchCamera');if(torch){torch.hidden=!capabilities.torch;torch.setAttribute('aria-pressed','false');}if(Array.isArray(capabilities.focusMode)&&capabilities.focusMode.includes('continuous'))track.applyConstraints?.({advanced:[{focusMode:'continuous'}]}).catch(()=>{});await video.play();if(session!==scannerSession||!activeProfileMatches()){stopCamera();return;}scanning=true;lastDetectionAt=0;setCameraUi(true);setCapability('Live camera','success');setStatus('<strong>Scanning…</strong> Hold the QR steady inside the frame.','active');scanFrame=requestAnimationFrame(scanLoop);}catch(error){if(session!==scannerSession){candidate?.getTracks?.().forEach(track=>track.stop());return;}stopCamera();const denied=error?.name==='NotAllowedError'||error?.name==='SecurityError';const message=denied?'Camera permission was not granted. You can retry, use your device QR scanner, or enter the spool ID.':(error?.message||'Camera scanning could not start.');setCapability(denied?'Camera permission needed':'Camera unavailable','warning');setStatus(`<strong>${automatic?'Camera did not start':'Camera unavailable'}.</strong> ${esc(message)}`,'warning');const fallback=$('qrScanFallback'),manual=$('qrManualDetails');if(fallback)fallback.hidden=false;if(manual)manual.open=true;requestAnimationFrame(()=>$('qrStartCamera')?.focus());}finally{if(session===scannerSession){startingCamera=false;const start=$('qrStartCamera');if(start&&!scanning)start.disabled=false;}}}

  async function scanLoop(timestamp){if(!scanning||!activeProfileMatches())return;const video=$('qrScannerVideo');if(!detecting&&video?.readyState>=2&&timestamp-lastDetectionAt>=140){detecting=true;lastDetectionAt=timestamp;try{const results=await detector.detect(video);if(!activeProfileMatches())return;const value=results?.find(row=>row?.rawValue)?.rawValue;if(value){const handled=await processScanValue(value,{fromCamera:true});if(handled)return;lastDetectionAt=timestamp+700;}}catch(error){console.warn('QR detection frame failed',error);}finally{detecting=false;}}if(scanning)scanFrame=requestAnimationFrame(scanLoop);}
  async function toggleTorch(){const track=stream?.getVideoTracks?.()[0]||stream?.getTracks?.()[0],button=$('qrTorchCamera');if(!track?.applyConstraints||!button||!activeProfileMatches())return;try{torchOn=!torchOn;await track.applyConstraints({advanced:[{torch:torchOn}]});button.setAttribute('aria-pressed',String(torchOn));button.textContent=torchOn?'Flashlight on':'Flashlight';}catch{torchOn=false;button.setAttribute('aria-pressed','false');button.hidden=true;}}
  function stopCamera(){scanning=false;detecting=false;startingCamera=false;torchOn=false;if(scanFrame)cancelAnimationFrame(scanFrame);scanFrame=0;stream?.getTracks?.().forEach(track=>track.stop());stream=null;detector=null;const video=$('qrScannerVideo');if(video)video.srcObject=null;const torch=$('qrTorchCamera');if(torch){torch.hidden=true;torch.textContent='Flashlight';torch.setAttribute('aria-pressed','false');}setCameraUi(false);}

  function openPhysicalSpool(id){const actions=globalThis.FilamentInventorySpoolActions;if((!actions?.openPhysical&&!actions?.open)||!findSpool(id))return false;closeScanner();$('scanSpoolDialog')?.close();if(actions.openPhysical)return actions.openPhysical(id,{source:'scan'})!==false;return actions.open(id,{source:'scan'})!==false;}
  function showUnknown(id){pendingUnknown=id;closeScanner();const dialog=document.querySelector('.qr-unknown-dialog');dialog.querySelector('[data-unknown-title]').textContent=`${id} not found here`;dialog.showModal();}
  function addUnknown(){const id=pendingUnknown;pendingUnknown='';document.querySelector('.qr-unknown-dialog')?.close();($('inventoryAddBtn')||$('heroAddBtn')||$('addTopBtn'))?.click();setTimeout(()=>{const field=$('spoolId');if(field){field.value=id;field.dispatchEvent(new Event('input',{bubbles:true}));field.focus();}},60);}
  function syncUnknown(){pendingUnknown='';document.querySelector('.qr-unknown-dialog')?.close();if(!globalThis.FilamentInventoryNavigation?.navigate?.('sync',{historyMode:'replace',focus:true}))document.querySelector('.tab[data-view="sync"]')?.click();}

  async function processScanValue(raw){if(scannerProfile&&!activeProfileMatches())return false;const parsed=core.parseScanValue(raw,location.origin);if(!parsed.ok){const message=parsed.reason==='foreign-origin'?'That QR points to a different site.':'No valid filament spool ID was found in that code.';setStatus(`<strong>Not a Filament Inventory label.</strong> ${esc(message)}`,'warning');return false;}stopCamera();const state=readState(),exists=core.stateHasSpool(state,parsed.spoolId),target=core.buildSpoolTarget({spoolId:parsed.spoolId},location.origin);if(exists){setStatus(`<strong>Found ${esc(parsed.spoolId)}.</strong> Opening spool controls…`,'success');setTimeout(()=>{if(!openPhysicalSpool(parsed.spoolId))location.assign(target);},60);return true;}showUnknown(parsed.spoolId);return true;}
  function bindUnknown(){document.addEventListener('click',event=>{const target=event.target instanceof Element?event.target:null;if(!target)return;if(target.closest('[data-unknown-close]')){pendingUnknown='';target.closest('dialog')?.close();return;}if(target.closest('[data-unknown-scan]')){pendingUnknown='';target.closest('dialog')?.close();openScanner();return;}if(target.closest('[data-unknown-add]')){addUnknown();return;}if(target.closest('[data-unknown-sync]')){syncUnknown();return;}const recent=target.closest('[data-scanner-recent-id]');if(recent)openPhysicalSpool(recent.dataset.scannerRecentId);});}

  function init(){ensureDialogs();ensureLaunchButton();bindUnknown();globalThis.FilamentInventoryScanner=Object.freeze({open:openScanner,close:closeScanner,stop:stopCamera,process:processScanValue});window.addEventListener('pagehide',()=>{invalidateScannerSession();stopCamera();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&scanning)stopCamera();});}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();