import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import test from 'node:test';
const read=p=>readFile(new URL(`../${p}`,import.meta.url),'utf8');

test('shell uses durable destinations and task-specific widths',async()=>{const js=await read('app-shell-client.js'); assert.match(js,/\['dashboard','Home'\]/); assert.match(js,/\['inventory','Inventory'\]/); assert.match(js,/\['household','Printer'\]/); assert.doesNotMatch(js,/PRIMARY[^;]*weigh/s); assert.match(js,/weigh:'focus'/); assert.match(js,/inventory:'workbench'/); assert.match(js,/household:'workbench'/);});
test('desktop shell separates destinations from quick actions',async()=>{const js=await read('app-shell-client.js'); assert.match(js,/Workspace/); assert.match(js,/Manage/); assert.match(js,/Settings/); assert.match(js,/Quick actions/); assert.match(js,/Can I print this\?/); assert.match(js,/Scan spool/); assert.match(js,/Add spool/); assert.match(js,/fi-nav-icon/);});
test('page headers own contextual actions and legacy page headings are suppressed',async()=>{const js=await read('app-shell-client.js'); const css=await read('css/components/app-shell.css'); assert.match(js,/PAGE_ACTIONS/); assert.match(js,/inventoryAddBtn/); assert.match(js,/exportHistoryBtn/); assert.match(js,/installBtn/); assert.match(js,/fi-page-header-actions/); assert.match(js,/fi-legacy-page-head/); assert.match(css,/\.fi-legacy-page-head\s*\{\s*display:none/);});
test('visible mobile navigation is singular and consistently named',async()=>{const js=await read('app-shell-client.js'); const css=await read('css/components/app-shell.css'); assert.match(js,/data-bottom-scan/); assert.match(js,/inventory\.textContent='Inventory'/); assert.match(css,/\.fi-app-frame\.fi-v10 \.app-shell > \.tabs\s*\{\s*display:none/);});
test('home and topbar are reduced to operational hierarchy',async()=>{const js=await read('app-shell-client.js'); const css=await read('css/components/app-shell.css'); assert.match(js,/Start with the print\. Choose the right spool\./); assert.match(js,/Private filament workspace/); assert.match(js,/fi-global-duplicate/); assert.match(css,/\.fi-global-duplicate\s*\{\s*display:none/); assert.match(css,/\.fi-home-compact/);});
test('shell architecture CSS avoids emergency specificity escapes',async()=>{const css=await read('css/components/app-shell.css'); assert.doesNotMatch(css,/!important/); assert.doesNotMatch(css,/(^|[\s,{])#[A-Za-z_-]/m);});
test('shell assets are published and activated',async()=>{const assets=await read('scripts/public-assets.mjs'); const html=await read('index.html'); assert.match(assets,/'css\/components\/app-shell\.css'/); assert.match(assets,/'app-shell-client\.js'/); assert.match(html,/href="\/css\/components\/app-shell\.css"/); assert.match(html,/src="\/app-shell-client\.js"/);});
