(()=>{
  const $=id=>document.getElementById(id);
  const set=(id,v)=>{const e=$(id);if(e&&v!==undefined&&v!==null)e.textContent=v};
  const fmt=u=>u<60?`${u}s`:u<3600?`${Math.floor(u/60)}m`:`${Math.floor(u/3600)}h ${Math.floor((u%3600)/60)}m`;
  const fToF=c=>Math.round((Number(c)||0)*9/5+32);
  const airNames=['Off','Manual','Auto','Post-print'];
  let lastSyncAt=0,lastData=null,syncing=false,failures=0,syncTimer=null;
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const toast=(m,bad=false)=>{const t=$('consoleToast');if(!t)return;t.textContent=m;t.style.borderColor=bad?'#6a3840':'#31515d';t.style.color=bad?'#ffadb4':'#dcecf1';t.style.opacity='1';t.style.transform='translateY(0)';clearTimeout(window.__whToast);window.__whToast=setTimeout(()=>{t.style.opacity='0';t.style.transform='translateY(8px)'},4200)};
  const announce=m=>{const e=$('statusAnnouncer');if(e)e.textContent=m};
  const signal=r=>r>=-55?['Excellent','excellent']:r>=-67?['Good','good']:r>=-75?['Fair','fair']:['Weak','weak'];
  function ensureProgress(cardId,trackId,metaId){const value=$(cardId);const card=value?.closest('.command-card');if(!card||$(trackId))return;const track=document.createElement('div');track.className='live-progress';track.innerHTML=`<span id='${trackId}'></span>`;const meta=document.createElement('div');meta.id=metaId;meta.className='progress-meta';card.append(track,meta)}
  function ensureDeck(){if($('liveDeck'))return;const now=$('now');if(!now)return;const deck=document.createElement('div');deck.id='liveDeck';deck.className='live-deck';deck.setAttribute('aria-label','Quick device controls');deck.innerHTML=`<span class='deck-label'>Quick control</span><button class='deck-action muted' data-deck-action='/update/check' data-label='Check update'>Check update</button><button class='deck-action muted' data-deck-action='/audio/test' data-label='Test speaker'>Test speaker</button><button class='deck-action muted' data-deck-action='/wifi/reconnect' data-label='Reconnect Wi-Fi'>Reconnect</button><span class='deck-separator'></span><button id='deckPause' class='deck-action muted' data-deck-action='/bambu/pause' data-label='Pause printer'>Pause print</button><button id='deckResume' class='deck-action muted' data-deck-action='/bambu/resume' data-label='Resume printer'>Resume print</button><span class='deck-spacer'></span><span id='deckStatus' class='deck-status'>Live</span>`;now.insertAdjacentElement('afterend',deck);deck.querySelectorAll('[data-deck-action]').forEach(b=>b.addEventListener('click',()=>runAction(b.dataset.deckAction,b.dataset.label,b)))}
  function ensureEnhancements(){ensureDeck();ensureProgress('nowPrinter','printerProgressBar','printerProgressMeta');const updater=$('liveOta')?.closest('.health-row');if(updater&&!$('otaProgressBar')){const p=document.createElement('div');p.className='live-progress health-progress';p.innerHTML="<span id='otaProgressBar'></span>";updater.insertAdjacentElement('afterend',p)}if(!$('statusAnnouncer')){const e=document.createElement('div');e.id='statusAnnouncer';e.className='sr-live';e.setAttribute('aria-live','polite');document.body.appendChild(e)}}
  function updateStatusDot(cardId,on,warn=false){const card=$(cardId)?.closest('.command-card');const dot=card?.querySelector('.command-status');if(!dot)return;dot.classList.toggle('off',!on);dot.classList.toggle('warn',!!warn);card.dataset.active=on?'true':'false'}
  function paintAttention(d){const box=$('attentionList');if(!box)return;const items=d.attention?.items||[];set('attentionCount',items.length);if(!items.length){box.innerHTML="<div class='nominal'><span class='nominal-icon'>✓</span><div><strong>All systems nominal</strong><small>No active device, printer, weather or workshop alerts.</small></div></div>";return}box.innerHTML=items.slice().sort((a,b)=>(Number(b.severity)||0)-(Number(a.severity)||0)).slice(0,8).map(a=>{const sev=['info','attention','urgent'][Number(a.severity)||0]||'info';return `<div class='attention-item ${sev}'><span class='attention-dot'></span><div class='attention-copy'><strong>${esc(a.title)}</strong><small>${esc(a.detail)}</small></div><span class='attention-source'>${esc(a.source)}</span></div>`}).join('')}
  function integrationRow(name,x){let klass='',state='Not configured';if(x?.enabled||x?.configured){if(x?.online||x?.ready){klass='online';state='Online'}else{klass='warn';state=x?.configured?'Unavailable':'Enabled'}}return `<div class='integration-row ${klass}'><span class='health-dot'></span><span class='integration-name'>${esc(name)}</span><span class='integration-state'>${esc(state)}</span></div>`}
  function paintIntegrations(d){const box=$('integrationHealth');if(!box)return;const x=d.integrations||{};box.innerHTML=integrationRow('Weather',x.weather)+integrationRow('Bambu Lab',x.printer)+integrationRow('Filament inventory',x.filament)+integrationRow('Home Assistant',x.homeAssistant)+integrationRow('Calendar',x.calendar)+integrationRow('Speaker',x.audio)}
  function paintProgress(d){const p=Math.max(0,Math.min(100,Number(d.printer?.progress)||0));const bar=$('printerProgressBar');if(bar)bar.style.width=`${p}%`;const meta=$('printerProgressMeta');if(meta)meta.innerHTML=d.printer?.online&&p>0?`<span>Layer ${d.printer.layer||0}/${d.printer.totalLayers||0}</span><span>${d.printer.remainingMinutes||0} min remaining</span>`:`<span>${d.printer?.online?'Printer ready':'Printer offline'}</span><span>${p}%</span>`;const ota=d.ota?.total?Math.min(100,Math.round((d.ota.bytes||0)*100/d.ota.total)):0;const ob=$('otaProgressBar');if(ob)ob.style.width=`${d.ota?.inProgress?ota:0}%`;set('deckStatus',d.ota?.inProgress?`OTA ${ota}%`:(d.printer?.online&&p>0?`Print ${p}%`:'Live'))}
  function applyStatus(d){
    ensureEnhancements();lastData=d;lastSyncAt=Date.now();failures=0;document.body.classList.remove('stale-data');set('liveFirmware',d.firmware);set('liveSsid',d.network?.connected?d.network.ssid:'Offline');const rssi=Number(d.network?.rssi??0),sig=signal(rssi);const ip=$('liveIp');if(ip)ip.innerHTML=`${esc(d.network?.ip||'Offline')} • ${rssi} dBm • <span class='signal ${sig[1]}'>${sig[0]}</span>`;set('liveUptime',fmt(d.system?.uptimeSec||0));set('liveAlerts',d.attention?.count??d.alerts??0);set('liveBoot',d.system?.stableBoot?'Stable':'Validating');set('liveSlot',`${d.ota?.runningPartition||'?'} → ${d.ota?.nextPartition||'?'}`);
    const otaPct=d.ota?.total?Math.min(100,Math.round((d.ota.bytes||0)*100/d.ota.total)):0;set('liveOta',d.ota?.inProgress?`${d.ota.status||'Updating'} • ${otaPct}%`:(d.updater?.error||d.updater?.status||'Idle'));set('liveWeather',d.weather?.online?`${fToF(d.weather.temperatureC)}°F • ${d.weather.condition}`:(d.weather?.condition||'Unavailable'));
    const online=$('liveOnline');if(online){online.textContent=d.network?.connected?'ONLINE':'OFFLINE';online.className=`pill ${d.network?.connected?'good':'bad'}`};const dot=$('liveDot');if(dot)dot.style.opacity=d.network?.connected?'1':'.35';
    if(d.weather?.online){set('nowWeather',`${fToF(d.weather.temperatureC)}°F`);const el=$('nowWeather')?.nextElementSibling;if(el)el.textContent=`${d.weather.condition} • H ${fToF(d.weather.highC)}° / L ${fToF(d.weather.lowC)}° • rain ${d.weather.precipitationPercent||0}%`;updateStatusDot('nowWeather',true,!!d.weather.severeAlert)}else{set('nowWeather','Unavailable');updateStatusDot('nowWeather',false)}
    if(d.printer?.online){set('nowPrinter',d.printer.progress>0?`${d.printer.progress}%`:(d.printer.status||'Ready'));const el=$('nowPrinter')?.nextElementSibling;if(el)el.textContent=d.printer.progress>0?`${d.printer.job||'Print'} • ${d.printer.remainingMinutes||0} min left`:`${d.printer.name||'Bambu Lab'}${d.printer.model?` • ${d.printer.model}`:''}`;updateStatusDot('nowPrinter',true,!!d.printer.errorCode)}else{set('nowPrinter',d.printer?.configured?'Offline':'Not set up');updateStatusDot('nowPrinter',false)}
    const env=d.workshop?.environment;if(env?.online&&!env.stale){set('nowWorkshop',`${Math.round(env.humidity||0)}% RH`);const el=$('nowWorkshop')?.nextElementSibling;if(el)el.textContent=`PM2.5 ${Number(env.pm25||0).toFixed(1)} • VOC ${Math.round(env.voc||0)}`;updateStatusDot('nowWorkshop',true)}else{set('nowWorkshop','No sensor');const el=$('nowWorkshop')?.nextElementSibling;if(el)el.textContent=`Air mode: ${airNames[d.workshop?.airMode||0]}`;updateStatusDot('nowWorkshop',false)}
    if(d.audio){set('nowAudio',d.audio.enabled?`${d.audio.volume}%`:'Off');updateStatusDot('nowAudio',!!d.audio.ready)}paintAttention(d);paintIntegrations(d);paintProgress(d);set('lastRefresh','Updated now');const pp=Number(d.printer?.progress)||0;const pause=$('deckPause'),resume=$('deckResume');if(pause)pause.disabled=!d.printer?.online||pp<=0;if(resume)resume.disabled=!d.printer?.online;announce(`Dashboard updated. ${d.attention?.count??d.alerts??0} active alerts.`)
  }
  function scheduleSync(ms){clearTimeout(syncTimer);syncTimer=setTimeout(()=>sync(),ms)}
  async function sync(manual=false){if(syncing)return;syncing=true;if(manual)set('lastRefresh','Refreshing…');try{const r=await fetch('/api/status',{cache:'no-store'});if(!r.ok)throw new Error(`status ${r.status}`);applyStatus(await r.json());scheduleSync(5000)}catch(e){failures++;const on=$('liveOnline');if(on){on.textContent='STALE';on.className='pill warn'}document.body.classList.add('stale-data');set('lastRefresh','Refresh failed');set('deckStatus','Degraded');if(manual)toast('Could not refresh device status',true);scheduleSync(Math.min(30000,5000*Math.pow(1.6,failures)))}finally{syncing=false}}
  async function runAction(path,label,button,fields={}){if(button)button.classList.add('action-busy');try{const fd=new FormData();Object.entries(fields).forEach(([k,v])=>fd.append(k,v));const r=await fetch(path,{method:'POST',body:fd});const text=await r.text();toast(text,!r.ok);announce(`${label}: ${text}`);await sync()}catch(e){toast(`${label} failed`,true)}finally{if(button)button.classList.remove('action-busy')}}
  function bindAudio(){const slider=$('audioVolume'),label=$('audioVolumeValue');if(slider&&label){const paint=()=>label.textContent=`${slider.value}%`;slider.addEventListener('input',paint);paint()}document.querySelectorAll('[data-audio-volume]').forEach(b=>b.addEventListener('click',()=>{if(!slider)return;slider.value=b.dataset.audioVolume;slider.dispatchEvent(new Event('input',{bubbles:true}))}))}
  function bindConfirm(){document.querySelectorAll('[data-confirm]').forEach(el=>el.addEventListener('click',e=>{if(!confirm(el.dataset.confirm||'Continue?'))e.preventDefault()}))}
  function bindNav(){const links=[...document.querySelectorAll('.nav a[href^="#"]')];const map=new Map(links.map(a=>[a.getAttribute('href').slice(1),a]));const activate=id=>{links.forEach(a=>{const active=a===map.get(id);a.classList.toggle('active',active);active?a.setAttribute('aria-current','true'):a.removeAttribute('aria-current')})};const obs=new IntersectionObserver(entries=>{const hit=entries.filter(e=>e.isIntersecting).sort((a,b)=>b.intersectionRatio-a.intersectionRatio)[0];if(hit)activate(hit.target.id)},{rootMargin:'-12% 0px -72% 0px',threshold:[0,.15,.4]});map.forEach((_,id)=>{const el=$(id);if(el)obs.observe(el)});links.forEach(a=>a.addEventListener('click',()=>activate(a.getAttribute('href').slice(1))))}
  function bindAsyncActions(){document.querySelectorAll("form[data-async='1']").forEach(form=>form.addEventListener('submit',async e=>{e.preventDefault();const btn=form.querySelector('button');if(btn)btn.disabled=true;try{const r=await fetch(form.action,{method:(form.method||'POST').toUpperCase(),body:new FormData(form)});const text=await r.text();toast(text,!r.ok);await sync()}catch(err){toast('Request failed',true)}finally{if(btn)btn.disabled=false}}))}
  function clock(){const e=$('localClock');if(e)e.textContent=new Intl.DateTimeFormat(undefined,{hour:'numeric',minute:'2-digit',second:'2-digit'}).format(new Date());if(lastSyncAt){const age=Math.floor((Date.now()-lastSyncAt)/1000);if($('lastRefresh')&&age>12)set('lastRefresh',`Updated ${age}s ago`);document.body.classList.toggle('stale-data',age>20)}}
  ensureEnhancements();bindAudio();bindConfirm();bindNav();bindAsyncActions();$('manualRefresh')?.addEventListener('click',()=>sync(true));sync();clock();setInterval(clock,1000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)sync(true)});
})();
