export const PUBLIC_ASSETS = Object.freeze([
  'index.html',
  'styles.css',
  'ui-system.css',
  'app-version.js',
  'user-isolation.js',
  'app.js',
  'state-merge.js',
  'audit-core.js',
  'personal-core.js',
  'intake-core.js',
  'weigh-core.js',
  'scan-core.js',
  'printer-core.js',
  'inventory-command-core.js',
  'spool-actions-core.js',
  'bulk-actions-core.js',
  'sync-client.js',
  'security-client.js',
  'labels-client.js',
  'household-client.js',
  'ux-client.js',
  'audit-client.js',
  'personal-dashboard.js',
  'intake-client.js',
  'weigh-client.js',
  'scan-client.js',
  'printer-dashboard.js',
  'inventory-command-client.js',
  'spool-actions-client.js',
  'bulk-actions-client.js',
  'ui-v10-client.js',
  'sw.js',
  'manifest.webmanifest',
  'icon.svg',
  'robots.txt',
]);

export const JAVASCRIPT_ASSETS = Object.freeze(
  PUBLIC_ASSETS.filter((asset) => asset.endsWith('.js')),
);
